---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v2
  labels:
    app: details
    version: v2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: details
      version: v2
  template:
    metadata:
      labels:
        app: details
        version: v2
    spec:
      serviceAccountName: bookinfo-details
      containers:
      - name: details
        image: shaikkhajaibrahim/details:v3
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9080
        env:
          - name: SERVICE_VERSION
            value: v-50-50-unhealthy