apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details-route
spec:
  hosts:
  - "*"
  http:
  - name: "details-route"
    route:
    - destination:
        host: details